language: node_js
node_js:
- 10
branches:
  only:
  - prod
deploy:
  provider: firebase
  project: "milagros-0"
  token:
    secure: Sgf0lle+MWqOWH4i+vPV91F1akhJNDj5kOstvU5rXA0FwJiNgRt887VLoHuX6VbLQIWH9i8HyOANCxS7EPbLhtImjOShKE34bc0DO7Pb5rwkBPvJUZDIz9oIQnAEQ8uz16FGV8K1PmHto/hX2awZ6rtQJynR6cRJVY1+WFmJhmS9y2imq4dfn+5wFTxDiuKeIrfSPSiPkdJ3FcxZ34dyaKN4GHwH7QwOYdBD8XllkFi8D/e7u432IOeCLqhE+0lRCSzuBEwbWtLa09VqEwzgS/CrXG+5pM5qqRpkM8HnzCPbJK15XgQ27YK8IiBIJTJ1rikLcy7no3h3vzjVBdCFVem8uFUC7lYJjmCi6tFz4gwcgTxsXaa6tVtkZaFDvrITM3nzZEZ0BVGYrgxWJsWjBk2Ft4n48ViK6izFl0poz1N5DCBJJF9u9PBplBQ9rVmtA1ALHf0nPn0ZeYwJ6i10ktPKMPqoJ/C8q/FdSuo0TxLneEbOEv2sCXiHe7bU+EMAUfM5psflrF5u5jk2NayBq49R0TIRhmvdiR41SUTwUZmG6NUmxYfX6GpesmPAtydbgEMJ4SNCWJKlceWdCTJPgeuuwfFHdbZiC2XJFy7H57p4aZDTHM15ybb9/fR787FIEhjHYsYIfDYKmwZtMWfG6ts7K1v2dWfetCUyjSv7nYg=